services:
  drive:
    image: drive:v6
    container_name: drive
    restart: unless-stopped
    ports:
      - "127.0.0.1:8091:8091"
    env_file:
      - .env
    user: "65532:65532"
    environment:
      - DATABASE_PATH=/app/data/database.db
      - THUMBS_DIR=/app/data/thumbs
      - TEMP_DIR=/app/data/temp
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - YTDLP_PATH=/usr/local/bin/yt-dlp
      - TORRENT_PATH=/usr/bin/aria2c
    volumes:
      - ./data:/app/data
